name: PHPCS PSR12 & PHPUnit

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    paths:
      - '**.php'


jobs:
  phpcs-phpunit-check:
    name: PHP-CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install

      - name: Run check script with phpcs
        run: composer run check

      - name: Run test script with phpunit
        run: composer run test